-- Tabla FACTURA
CREATE TABLE FACTURA (
    FAC_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    FECHA_HORA DATETIME NOT NULL,
    TOTAL NUMERIC(18,2) NOT NULL,
    ID_OP VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_OP) REFERENCES OPERADORES(U_ID)
);

-- Tabla DETALLE_FACTURA
CREATE TABLE DETALLE_FACTURA (
    FAC_DET_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO NUMERIC(12,2) NOT NULL,
    SUBTOTAL NUMERIC(18,2) NOT NULL,
    ID_FACTURA INT NOT NULL,
    ID_PRODUCTO VARCHAR(13) NOT NULL,
    FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(FAC_ID),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(PROD_ID)
);

-- Tabla PRODUCTOS
CREATE TABLE PRODUCTOS (
    PROD_ID VARCHAR(13) PRIMARY KEY NOT NULL,
    DESCRIPCION VARCHAR(60) NOT NULL,
    STOCK INT,
    PRECIO_UNITARIO NUMERIC(12,2) NOT NULL,
    FECHA_BAJA DATETIME DEFAULT NULL
);

-- Tabla PROVEEDORES
CREATE TABLE PROVEEDORES (
    PROV_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    REFERENCIA VARCHAR(80) NOT NULL,
    CONTACTO VARCHAR(20) NULL,
    MAIL VARCHAR(80) NULL,
    DIRECCION VARCHAR(100) NULL
);

-- Tabla PROVEEDORES_PRODUCTO
CREATE TABLE PROVEEDORES_PRODUCTO (
    ID_PROV INT NOT NULL,
    ID_PROD VARCHAR(13) NOT NULL,
    PRIMARY KEY (ID_PROV, ID_PROD),
    FOREIGN KEY (ID_PROV) REFERENCES PROVEEDORES(PROV_ID),
    FOREIGN KEY (ID_PROD) REFERENCES PRODUCTOS(PROD_ID)
);

-- Tabla PEDIDOS
CREATE TABLE PEDIDOS (
    OC_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    FECHA_SOLICITUD DATETIME NOT NULL,
    ESTADO VARCHAR(20) DEFAULT 'PENDIENTE',
    ID_OP VARCHAR(50) NOT NULL,
    ID_PROV INT NOT NULL,
    FOREIGN KEY (ID_OP) REFERENCES OPERADORES(U_ID),
    FOREIGN KEY (ID_PROV) REFERENCES PROVEEDORES(PROV_ID)
);

-- Tabla DETALLE_PEDIDO
CREATE TABLE DETALLE_PEDIDO (
    DET_OC_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    CANTIDAD INT NOT NULL,
    ID_PROD VARCHAR(13) NOT NULL,
    ID_OC INT NOT NULL,
    FOREIGN KEY (ID_PROD) REFERENCES PRODUCTOS(PROD_ID),
    FOREIGN KEY (ID_OC) REFERENCES PEDIDOS(OC_ID)
);

-- Tabla OPERADORES
CREATE TABLE OPERADORES (
    U_ID VARCHAR(50) PRIMARY KEY DEFAULT USER_NAME() NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    TIPO BIT NOT NULL DEFAULT 0,
    CONTRASEÑA VARCHAR NOT NULL,
    FECHA_BAJA DATE DEFAULT NULL
);